name: build

on:
  push:
    branches:    
      - 'develop'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set alias
      run: . .\alias.ps1
    - name: Build the docker-compose
      run: dev-amt build